### ISSUE TITLE
Undefined is not a function (evaluating 'addListener'

### ISSUE THREAD

**Issue by serge-fabiano** [GeekyAnts/ignite-native-base-boilerplate#22]
Create a project with 'ignite new ev-mobile --boilerplate native-base-boilerplate' and run it on Android under Windows and you'll get the error below:

undefined is not a function (evaluating 'addListener')
<unknown>
    C:\Data\dev\ev-mobile\node_modules\react-navigation\src\getChildEventSubscriber.js:60:16
getChildEventSubscriber
    C:\Data\dev\ev-mobile\node_modules\react-navigation\src\getChildEventSubscriber.js:59:49
_getScreenDetails
    C:\Data\dev\ev-mobile\node_modules\react-navigation\src\views\CardStack\CardStack.js:124:10
render
    C:\Data\dev\ev-mobile\node_modules\react-navigation\src\views\CardStack\CardStack.js:272:47
<unknown>
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1863:19
measureLifeCyclePerf
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1610:15
_renderValidatedComponentWithoutOwnerOrContext
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1862:54
_renderValidatedComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1872:34
performInitialMount
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1696:57
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1655:184
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
mountChildren
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2871:62
initializeChildren
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2940:45
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2969:84
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
performInitialMount
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1703:54
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1655:184
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
performInitialMount
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1703:54
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1655:184
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
performInitialMount
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1703:54
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1655:184
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
performInitialMount
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1703:54
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1655:184
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
performInitialMount
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1703:54
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1655:184
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
performInitialMount
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1703:54
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1655:184
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
performInitialMount
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1703:54
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1655:184
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
performInitialMount
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1703:54
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1655:184
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
mountChildren
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2871:62
initializeChildren
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2940:45
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2969:84
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
performInitialMount
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1703:54
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1655:184
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
performInitialMount
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1703:54
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1655:184
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
performInitialMount
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1703:54
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1655:184
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
performInitialMount
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1703:54
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1655:184
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
performInitialMount
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1703:54
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1655:184
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
mountChildren
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2871:62
initializeChildren
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2940:45
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2969:84
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
performInitialMount
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1703:54
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1655:184
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
mountChildren
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2871:62
initializeChildren
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2940:45
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2969:84
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
performInitialMount
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1703:54
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1655:184
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
performInitialMount
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1703:54
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1655:184
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
performInitialMount
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1703:54
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1655:184
mountComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1327:53
mountComponentIntoNode
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1998:50
perform
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1382:99
batchedMountComponentIntoNode
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2004:24
perform
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1382:99
batchedUpdates
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2077:139
batchedUpdates$1
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:1456:61
renderComponent
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:2032:45
render
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\Renderer\ReactNativeStack-dev.js:3258:46
renderApplication
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\ReactNative\renderApplication.js:34:4
run
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\ReactNative\AppRegistry.js:117:10
runApplication
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\ReactNative\AppRegistry.js:191:26
__callFunction
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:266:47
<unknown>
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:103:26
__guard
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:231:6
callFunctionReturnFlushedQueue
    C:\Data\dev\ev-mobile\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:102:17

**Comment by navneetccna** [comment]
getting same issue with this boilerplate

**Comment by serge-fabiano** [comment]
I bought a Mac :(

**Comment by navneetccna** [comment]
what is the solution ?
