### ISSUE TITLE
please tag a new release and allow to attach to StrapMobile projects

### ISSUE THREAD

**Issue by vesper8** [GeekyAnts/ignite-native-base-boilerplate#5]
2.0.0-rc.1 was released today and a lot of people are trying Ignite. Your boilerplate still shows the wrong name even though you fixed this a month ago. Could you please tag a new release?

And also, I have a project that is built with NativeBase and I want to ignite attach while specifying the boilerplate so : ignite attach --boilerplate native-base-boilerplate

How can I achieve this? I want to be able to create components and screens in this existing project using the native-base-boilerplate? If I can't do this in one command.. then how? Create a new project with the BP and then copy over which files and which folders?

Thanks

**Comment by vesper8** [comment]
I'm not at all able to install your boilerplate as I mention in my comment here https://github.com/infinitered/ignite/issues/1003#issuecomment-304210974

**Comment by sanketsahu** [comment]
I am trying my level best to take out some time to look into this. Give us sometime please.

**Comment by shivrajkumar** [comment]
Check the latest
